import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import CommonHeader from '@/shared/components/CommonHeader';
import I18nProvider from '@/shared/components/I18nProvider';
import NavButtons from '@/shared/components/NavButtons';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <I18nProvider>
          <header className={'flex flex-col px-4 pt-1'}>
            <CommonHeader />
          </header>
          <main>
            <div className="relative flex-1 flex flex-col gap-6 min-h-0">
              {children}
            </div>
            <NavButtons />
          </main>
        </I18nProvider>
      </body>
    </html>
  );
}
